// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Data;

namespace OnlineShop.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210126055210_addCategAndSubcateg")]
    partial class addCategAndSubcateg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineShop.Models.Categorie", b =>
                {
                    b.Property<string>("Nume_categorie")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descriere");

                    b.HasKey("Nume_categorie");

                    b.ToTable("Categorii");
                });

            modelBuilder.Entity("OnlineShop.Models.Subcategorie", b =>
                {
                    b.Property<string>("Nume_subcateg")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descriere");

                    b.Property<string>("Nume_categorie");

                    b.HasKey("Nume_subcateg");

                    b.HasIndex("Nume_categorie");

                    b.ToTable("Subcategorii");
                });

            modelBuilder.Entity("OnlineShop.Models.Subcategorie", b =>
                {
                    b.HasOne("OnlineShop.Models.Categorie", "Categorie")
                        .WithMany("Subgategorii")
                        .HasForeignKey("Nume_categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
